"""sdjkbvjsbvjhks vkds vjks

Revision ID: 462359e8fcc9
Revises: 6827bffaefb1
Create Date: 2020-12-03 16:33:32.946858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462359e8fcc9'
down_revision = '6827bffaefb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    # ### end Alembic commands ###
